# Generated by Django 3.1.2 on 2020-11-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytbl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinates',
            name='type_code',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
