# Generated by Django 3.1.2 on 2020-11-08 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ytbl', '0003_auto_20201106_1847'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coordinates',
        ),
    ]
