# Generated by Django 3.1.2 on 2020-11-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytbl', '0005_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinates',
            name='is_next_to',
            field=models.SmallIntegerField(),
        ),
    ]
