# Generated by Django 3.1.2 on 2020-11-10 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20201110_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='img_url',
        ),
    ]
