# Generated by Django 3.1.2 on 2020-11-11 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_remove_board_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='board.comment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='board_images'),
        ),
    ]
